# Generated by Django 3.0 on 2019-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='rate',
        ),
        migrations.AlterField(
            model_name='laundry',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
