# Generated by Django 3.0 on 2019-12-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191211_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
