# Generated by Django 3.0 on 2019-12-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191211_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='laundry',
            old_name='name',
            new_name='Name',
        ),
    ]
