# Generated by Django 3.0 on 2019-12-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PW', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('IsMale', models.BooleanField()),
                ('BirthDate', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('FavoriteLaundry', models.TextField()),
                ('FavoriteRepair', models.TextField()),
            ],
        ),
    ]
